import {PGlite} from "@electric-sql/pglite";
import {pgcrypto} from "@electric-sql/pglite/contrib/pgcrypto";
import {readFileSync,readdirSync} from "node:fs";
import {beforeAll,afterAll,describe,it,expect} from "vitest";
const admin="11111111-1111-4111-8111-111111111111";
const kiosk="22222222-2222-4222-8222-222222222222";
const outsider="33333333-3333-4333-8333-333333333333";
let db:PGlite;let employee:string;
async function asUser(id:string){await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id}',false);`)}
async function rpc<T=unknown>(name:string,args:unknown[]){const marks=args.map((_,i)=>`$${i+1}`).join(',');return (await db.query<{value:T}>(`select public.${name}(${marks}) value`,args)).rows[0].value;}
beforeAll(async()=>{
 db=new PGlite({extensions:{pgcrypto}});
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public to authenticated,anon;grant execute on function auth.uid() to authenticated;
 insert into auth.users values ('${admin}'),('${kiosk}'),('${outsider}');`);
 for(const file of readdirSync('supabase/migrations').sort())await db.exec(readFileSync('supabase/migrations/'+file,'utf8'));
 await db.exec(`insert into public.profiles values('${admin}','Administrador','admin'),('${kiosk}','Tablet','kiosk');insert into public.devices(user_id,name) values('${kiosk}','Tablet oficina');`);
 await asUser(admin);employee=await rpc<string>('create_employee',['RT001','Empleado de prueba','Pista','Pistero',50000000,'123456',10]);
},30000);
afterAll(async()=>{await db?.close()});
describe('Migraciones y seguridad PostgreSQL',()=>{
 it('kiosk no puede leer empleados, hashes ni planillas',async()=>{await asUser(kiosk);expect((await db.query('select * from public.employees')).rows).toHaveLength(0);expect((await db.query('select * from public.payroll_items')).rows).toHaveLength(0);await expect(db.query('select * from public.employee_secrets')).rejects.toThrow();});
 it('usuarios sin rol no pueden crear empleados',async()=>{await asUser(outsider);await expect(rpc('create_employee',['RT002','Otro empleado','Tienda','Vendedor',100,'123456',0])).rejects.toThrow();});
 it('no permite suplantar roles ni editar eventos',async()=>{await asUser(kiosk);await expect(db.query(`update public.profiles set role='admin' where id=$1`,[kiosk])).rejects.toThrow();await expect(db.query('delete from public.attendance_events')).rejects.toThrow();});
 it('un PIN null no permite marcar',async()=>{await asUser(kiosk);const result=await rpc<{error:string}>('register_punch',['RT001',null,'entry',crypto.randomUUID()]);expect(result.error).toContain('incorrecto');});
 it('valida el flujo e idempotencia',async()=>{await asUser(kiosk);const id=crypto.randomUUID();const first=await rpc<{ok:boolean;at:string}>('register_punch',['RT001','123456','entry',id]);expect(first.ok).toBe(true);expect(await rpc('register_punch',['RT001','123456','entry',id])).toEqual(first);expect((await rpc<{error:string}>('register_punch',['RT001','123456','entry',crypto.randomUUID()])).error).toContain('abierta');expect((await rpc<{ok:boolean}>('register_punch',['RT001','123456','break_start',crypto.randomUUID()])).ok).toBe(true);expect((await rpc<{error:string}>('register_punch',['RT001','123456','exit',crypto.randomUUID()])).error).toContain('descanso');expect((await rpc<{ok:boolean}>('register_punch',['RT001','123456','break_end',crypto.randomUUID()])).ok).toBe(true);expect((await rpc<{ok:boolean}>('register_punch',['RT001','123456','exit',crypto.randomUUID()])).ok).toBe(true);await asUser(admin);expect((await db.query('select * from public.attendance_events')).rows).toHaveLength(4);});
 it('aprobar vacaciones descuenta una vez y rechaza sobregiro',async()=>{await asUser(admin);const {rows}=await db.query<{id:string}>(`insert into public.absences(employee_id,kind,starts_on,ends_on,vacation_days) values($1,'vacation','2026-10-05','2026-10-06',2) returning id`,[employee]);await rpc('review_absence',[rows[0].id,'approved']);await expect(rpc('review_absence',[rows[0].id,'approved'])).rejects.toThrow();expect((await db.query<{vacation_balance:string}>('select vacation_balance from public.employees where id=$1',[employee])).rows[0].vacation_balance).toBe('8.00');const over=(await db.query<{id:string}>(`insert into public.absences(employee_id,kind,starts_on,ends_on,vacation_days) values($1,'vacation','2026-11-01','2026-11-20',20) returning id`,[employee])).rows[0];await expect(rpc('review_absence',[over.id,'approved'])).rejects.toThrow();expect((await db.query<{status:string}>('select status from public.absences where id=$1',[over.id])).rows[0].status).toBe('pending');});
 it('el cierre exige revisión y bloquea cambios posteriores',async()=>{await asUser(admin);const run=await rpc<string>('create_payroll',['2026-08-01']);await expect(rpc('close_payroll',[run])).rejects.toThrow();const item=(await db.query<{id:string}>('select id from public.payroll_items where run_id=$1',[run])).rows[0];await rpc('update_payroll_item',[item.id,50000000,100,200,'Base y deducciones revisadas',true]);await rpc('close_payroll',[run]);await expect(rpc('update_payroll_item',[item.id,1,0,0,'Intento',true])).rejects.toThrow();await expect(db.query('update public.payroll_items set base_cents=1')).rejects.toThrow();});
 it('rechaza turnos superpuestos y acepta relevos contiguos',async()=>{await asUser(admin);await db.query(`insert into public.shifts(employee_id,starts_at,ends_at) values($1,'2026-10-01 06:00-06','2026-10-01 14:00-06')`,[employee]);await expect(db.query(`insert into public.shifts(employee_id,starts_at,ends_at) values($1,'2026-10-01 13:00-06','2026-10-01 18:00-06')`,[employee])).rejects.toThrow();await db.query(`insert into public.shifts(employee_id,starts_at,ends_at) values($1,'2026-10-01 14:00-06','2026-10-01 18:00-06')`,[employee]);});
 it('no permite cerrar un período futuro',async()=>{await asUser(admin);const run=await rpc<string>('create_payroll',['2099-01-01']);const item=(await db.query<{id:string}>('select id from public.payroll_items where run_id=$1',[run])).rows[0];await rpc('update_payroll_item',[item.id,50000000,0,0,'Conceptos revisados',true]);await expect(rpc('close_payroll',[run])).rejects.toThrow(/terminado/);});
 it('ajusta una jornada nocturna sin borrar eventos y cierra la sesión derivada',async()=>{await db.exec('reset role');const session=(await db.query<{id:string}>(`insert into public.attendance_sessions(employee_id,started_at) values($1,'2026-07-31 22:00-06') returning id`,[employee])).rows[0];await asUser(admin);await rpc('correct_session',[session.id,'2026-07-31 22:00-06','2026-08-01 06:00-06',30,'Salida olvidada verificada por encargado']);const effective=(await db.query<{worked_hours:string;adjusted:boolean}>('select * from public.effective_sessions where id=$1',[session.id])).rows[0];expect(Number(effective.worked_hours)).toBe(7.5);expect(effective.adjusted).toBe(true);expect((await db.query('select * from public.attendance_sessions where id=$1 and ended_at is null',[session.id])).rows).toHaveLength(0);expect((await db.query('select * from public.attendance_events')).rows).toHaveLength(4);});
 it('rechaza ajustes en planillas cerradas',async()=>{await db.exec('reset role');const session=(await db.query<{id:string}>(`insert into public.attendance_sessions(employee_id,started_at,ended_at) values($1,'2026-08-10 06:00-06','2026-08-10 14:00-06') returning id`,[employee])).rows[0];await asUser(admin);await expect(rpc('correct_session',[session.id,'2026-08-10 06:00-06','2026-08-10 15:00-06',0,'Corrección posterior'])).rejects.toThrow(/cerrada/);});
 it('elimina un empleado con todo su historial solo con el código correcto',async()=>{await asUser(outsider);await expect(rpc('delete_employee',[employee,'RT001'])).rejects.toThrow();await asUser(admin);await expect(rpc('delete_employee',[employee,'RT999'])).rejects.toThrow(/no coincide/);await rpc('delete_employee',[employee,'RT001']);await db.exec('reset role');for(const t of ['employees','employee_secrets','attendance_sessions','attendance_events','shifts','absences','payroll_items'])expect((await db.query(`select 1 from public.${t} where ${t==='employees'?'id':'employee_id'}=$1`,[employee])).rows).toHaveLength(0);expect((await db.query(`select 1 from public.audit_log where table_name='employees' and operation='DELETE' and record_id=$1`,[employee])).rows).toHaveLength(1);});
 it('limita intentos fallidos sin revertir el contador',async()=>{await asUser(kiosk);for(let i=0;i<10;i++)await rpc('register_punch',['RT001','000000','entry',crypto.randomUUID()]);expect((await rpc<{error:string}>('register_punch',['RT001','123456','entry',crypto.randomUUID()])).error).toContain('bloqueada');});
});
