import Link from "next/link";import {requireRole} from "@/lib/auth";import {Heading,Panel,CollapsiblePanel,Table,Empty} from "@/components/admin-ui";import {ActionForm} from "@/components/action-form";import {correctSession} from "../actions";import {dateTime,todayCR} from "@/lib/format";
const MAX_OPEN_HOURS=12;
const isDate=(v:unknown):v is string=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v));
const addDays=(date:string,days:number)=>{const d=new Date(date+"T00:00:00Z");d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)};
const startCR=(date:string)=>new Date(date+"T00:00:00-06:00").toISOString();
const openHours=(start:string)=>(Date.now()-new Date(start).getTime())/3600000;
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client}=await requireRole("admin");const params=await searchParams;const today=todayCR();
 let from=isDate(params.desde)?params.desde:addDays(today,-6);let to=isDate(params.hasta)?params.hasta:today;if(from>to)[from,to]=[to,from];
 const employee=typeof params.empleado==="string"&&/^[0-9a-f-]{36}$/i.test(params.empleado)?params.empleado:"";
 let query=client.from("effective_sessions").select("*").gte("started_at",startCR(from)).lt("started_at",startCR(addDays(to,1))).order("started_at",{ascending:false}).limit(500);
 if(employee)query=query.eq("employee_id",employee);
 const [sessions,open,emp]=await Promise.all([query,client.from("effective_sessions").select("*").is("ended_at",null).order("started_at"),client.from("employees").select("id,code,full_name").order("full_name")]);
 if(sessions.error||open.error||emp.error)throw new Error("No se pudo cargar la asistencia");
 const names=new Map(emp.data?.map(e=>[e.id,`${e.full_name} (${e.code})`]));
 const missingExit=(s:{ended_at:string|null;started_at:string})=>!s.ended_at&&(s.started_at<startCR(today)||openHours(s.started_at)>MAX_OPEN_HOURS);
 const alerts=(open.data??[]).filter(missingExit);
 const rows=sessions.data??[];const correctable=[...alerts,...rows.filter(r=>!alerts.some(a=>a.id===r.id))];
 const link=(desde:string,hasta:string)=>`/admin/asistencia?${new URLSearchParams({desde,hasta,...(employee?{empleado:employee}:{})})}`;
 const presets=[{label:"Hoy",from:today,to:today},{label:"Ayer",from:addDays(today,-1),to:addDays(today,-1)},{label:"Últimos 7 días",from:addDays(today,-6),to:today},{label:"Este mes",from:today.slice(0,8)+"01",to:today}];
 return <><Heading title="Asistencia" description="Revisa jornadas y registra ajustes sin borrar las marcaciones originales."/>
 {alerts.length>0&&<section className="panel attendance-alerts" role="alert"><h2>⚠ {alerts.length===1?"1 jornada sin marca de salida":`${alerts.length} jornadas sin marca de salida`}</h2><p className="muted small">Estas jornadas son de días anteriores o llevan más de {MAX_OPEN_HOURS} horas abiertas. Corrígelas abajo en “Corregir una jornada” indicando la hora real de salida.</p><Table headers={["Empleado","Entrada","Tiempo abierta"]}>{alerts.map(s=><tr key={s.id}><td><strong>{names.get(s.employee_id)}</strong></td><td>{dateTime(s.started_at)}</td><td><span className="badge danger">{Math.floor(openHours(s.started_at))} h sin salida</span></td></tr>)}</Table></section>}
 <div className="notice"><strong>Descansos y cálculo salarial</strong><p>Las horas mostradas excluyen todos los descansos marcados. Son un dato operativo; el tratamiento de descansos remunerados y horas extras debe revisarse al calcular la planilla.</p></div>
 <Panel title="Filtrar jornadas"><div className="filter-presets">{presets.map(p=><Link key={p.label} href={link(p.from,p.to)} className={`badge${p.from===from&&p.to===to?" selected":""}`}>{p.label}</Link>)}</div><form className="filters" method="get"><label>Desde<input type="date" name="desde" defaultValue={from} max={today}/></label><label>Hasta<input type="date" name="hasta" defaultValue={to} max={today}/></label><label>Empleado<select name="empleado" defaultValue={employee}><option value="">Todos</option>{emp.data?.map(e=><option key={e.id} value={e.id}>{e.full_name} ({e.code})</option>)}</select></label><button>Filtrar</button></form></Panel>
 <Panel title={from===to?`Jornadas del ${from}`:`Jornadas del ${from} al ${to}`}>{!rows.length?<Empty text="No hay jornadas en este rango."/>:<Table headers={["Empleado","Entrada","Salida","Horas operativas","Estado"]}>{rows.map(s=><tr key={s.id}><td>{names.get(s.employee_id)}</td><td>{dateTime(s.started_at)}</td><td>{s.ended_at?dateTime(s.ended_at):<span className={missingExit(s)?"text-danger":undefined}>Sin salida</span>}</td><td>{s.worked_hours===null?"—":Number(s.worked_hours).toFixed(2)}</td><td>{missingExit(s)?<span className="badge danger">Falta salida</span>:<span className="badge">{s.adjusted?"Ajustada":s.ended_at?"Completa":"En turno"}</span>}</td></tr>)}</Table>}{rows.length===500&&<p className="muted small">Se muestran las primeras 500 jornadas. Reduce el rango para ver el resto.</p>}</Panel>
 <CollapsiblePanel title="Corregir una jornada"><p className="muted small">El ajuste deja un motivo y el usuario responsable. Para cambios posteriores, consulta el historial de auditoría.</p><ActionForm action={correctSession}><label>Jornada<select name="session_id" defaultValue="" required><option value="" disabled>Selecciona una jornada</option>{correctable.map(s=><option value={s.id} key={s.id}>{missingExit(s)?"⚠ Sin salida · ":""}{names.get(s.employee_id)} · {dateTime(s.started_at)}</option>)}</select></label><label>Entrada correcta<input name="started_at" type="datetime-local" required/></label><label>Salida correcta<input name="ended_at" type="datetime-local" required/></label><label>Descanso total (minutos)<input name="break_minutes" type="number" defaultValue="0" min="0" max="1440" required/></label><label>Motivo<input name="reason" minLength={5} maxLength={500} required/></label></ActionForm></CollapsiblePanel></>}
