"use server";
import {revalidatePath} from "next/cache";import {z} from "zod";import {requireRole} from "@/lib/auth";import {employeeSchema,dateSchema} from "@/lib/schemas";import {crcToCents,calculatePayroll} from "@/lib/payroll";import type {ActionState} from "@/components/action-form";
function fields(form:FormData){return Object.fromEntries(form.entries())}
function failure(error:unknown):ActionState{if(error instanceof z.ZodError)return {error:"Revisa los campos del formulario."};return {error:error instanceof Error?error.message:"No se pudo guardar el registro."};}
function dbError(error:{message:string;code?:string}|null){if(error){if(error.code==="23505")throw new Error("Ya existe un registro con esos datos.");if(error.code==="23514")throw new Error("Los valores no cumplen las condiciones o el saldo disponible.");throw new Error(error.code==="P0001"?error.message:"No se pudo guardar. Revisa los datos y los permisos.");}}
export async function createEmployee(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=employeeSchema.parse(fields(form));const {error}=await client.rpc("create_employee",{p_code:v.code,p_name:v.full_name,p_department:v.department,p_position:v.position,p_salary:crcToCents(v.salary),p_pin:v.pin,p_vacation:v.vacation_balance});dbError(error);revalidatePath("/admin");revalidatePath("/admin/empleados");return {success:"Empleado registrado. Entrega el código y PIN de forma privada."};}catch(e){return failure(e)}}
export async function resetPin(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({employee_id:z.uuid(),pin:z.string().regex(/^\d{6,8}$/)}).parse(fields(form));const {error}=await client.rpc("set_employee_pin",{p_employee:v.employee_id,p_pin:v.pin});dbError(error);return {success:"PIN actualizado."}}catch(e){return failure(e)}}
export async function toggleEmployee(form:FormData){const {client}=await requireRole("admin");const id=z.uuid().parse(form.get("id"));const {error}=await client.rpc("set_employee_active",{p_employee:id,p_active:form.get("active")==="true"});dbError(error);revalidatePath("/admin/empleados")}
export async function vacationBalance(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({employee_id:z.uuid(),days:z.coerce.number().min(-365).max(365).refine(n=>n!==0),reason:z.string().trim().min(5).max(500)}).parse(fields(form));const {error}=await client.rpc("add_vacation_balance",{p_employee:v.employee_id,p_days:v.days,p_reason:v.reason});dbError(error);revalidatePath("/admin/empleados");return {success:"Saldo ajustado y movimiento registrado."}}catch(e){return failure(e)}}
export async function createShift(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({employee_id:z.uuid(),starts_at:z.string().min(16),ends_at:z.string().min(16),note:z.string().max(500)}).parse(fields(form));const starts=new Date(v.starts_at+":00-06:00");const ends=new Date(v.ends_at+":00-06:00");if(!Number.isFinite(starts.getTime())||!Number.isFinite(ends.getTime())||ends<=starts||ends.getTime()-starts.getTime()>86400000)throw new Error("El fin debe ser posterior al inicio y la duración no debe superar 24 horas.");const {error}=await client.from("shifts").insert({...v,starts_at:starts.toISOString(),ends_at:ends.toISOString()});dbError(error);revalidatePath("/admin/turnos");return {success:"Turno registrado."}}catch(e){return failure(e)}}
export async function createAbsence(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({employee_id:z.uuid(),kind:z.enum(["vacation","sick","permission"]),starts_on:dateSchema,ends_on:dateSchema,vacation_days:z.coerce.number().min(0).max(365),note:z.string().max(1000)}).parse(fields(form));if(v.ends_on<v.starts_on)throw new Error("Revisa las fechas.");if(v.kind==="vacation"&&v.vacation_days<=0)throw new Error("Indica los días laborables de vacaciones que corresponden.");const {error}=await client.from("absences").insert({...v,vacation_days:v.kind==="vacation"?v.vacation_days:0});dbError(error);revalidatePath("/admin/ausencias");return {success:"Ausencia registrada, pendiente de revisión."}}catch(e){return failure(e)}}
export async function reviewAbsence(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const id=z.uuid().parse(form.get("id"));const status=z.enum(["approved","rejected"]).parse(form.get("status"));const {error}=await client.rpc("review_absence",{p_id:id,p_status:status});dbError(error);revalidatePath("/admin/ausencias");revalidatePath("/admin/empleados");return {success:"Revisión guardada."}}catch(e){return failure(e)}}
export async function correctSession(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({session_id:z.uuid(),started_at:z.string().min(16),ended_at:z.string().min(16),break_minutes:z.coerce.number().int().min(0).max(1440),reason:z.string().trim().min(5).max(500)}).parse(fields(form));const start=new Date(v.started_at+":00-06:00");const end=new Date(v.ended_at+":00-06:00");if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start||end.getTime()-start.getTime()<v.break_minutes*60000)throw new Error("Revisa las fechas y el descanso.");const {error}=await client.rpc("correct_session",{p_session:v.session_id,p_start:start.toISOString(),p_end:end.toISOString(),p_break:v.break_minutes,p_reason:v.reason});dbError(error);revalidatePath("/admin/asistencia");return {success:"Ajuste registrado. Las marcaciones originales se conservan."}}catch(e){return failure(e)}}
export async function createPayroll(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const month=z.string().regex(/^\d{4}-\d{2}$/).parse(form.get("month"));dateSchema.parse(month+"-01");const {error}=await client.rpc("create_payroll",{p_month:month+"-01"});dbError(error);revalidatePath("/admin/planilla");return {success:"Preplanilla creada con los salarios base. Revisa cada empleado."}}catch(e){return failure(e)}}
export async function updatePayroll(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const id=z.uuid().parse(form.get("id"));const base=crcToCents(String(form.get("base")));const additions=crcToCents(String(form.get("additions")));const deductions=crcToCents(String(form.get("deductions")));calculatePayroll({baseCents:base,additionCents:additions,deductionCents:deductions});const note=z.string().max(2000).parse(form.get("note"));const {error}=await client.rpc("update_payroll_item",{p_id:id,p_base:base,p_additions:additions,p_deductions:deductions,p_note:note,p_reviewed:form.get("reviewed")==="on"});dbError(error);revalidatePath("/admin/planilla");return {success:"Conceptos guardados."}}catch(e){return failure(e)}}
export async function closePayroll(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const id=z.uuid().parse(form.get("id"));const {error}=await client.rpc("close_payroll",{p_id:id});dbError(error);revalidatePath("/admin/planilla");return {success:"Planilla cerrada. Ya puedes descargar el reporte."}}catch(e){return failure(e)}}

export async function updateEmployee(_:ActionState,form:FormData):Promise<ActionState>{const {client}=await requireRole("admin");try{const v=z.object({id:z.uuid(),full_name:z.string().trim().min(3).max(120),department:z.enum(["Pista","Supermercado","Tienda","Transporte","Administración"]),position:z.string().trim().min(2).max(80),salary:z.string()}).parse(fields(form));const {error}=await client.rpc("update_employee",{p_id:v.id,p_name:v.full_name,p_department:v.department,p_position:v.position,p_salary:crcToCents(v.salary)});dbError(error);revalidatePath("/admin/empleados");return {success:"Datos actualizados. Las planillas existentes conservan su información histórica."}}catch(e){return failure(e)}}
