"use client";
import {useActionState,useEffect,useState} from "react";import {Trash2,TriangleAlert} from "lucide-react";import type {ActionState} from "./action-form";
export function DeleteEmployee({id,name,code,action}:{id:string;name:string;code:string;action:(state:ActionState,form:FormData)=>Promise<ActionState>}){
 const [state,formAction,pending]=useActionState(action,{});const [open,setOpen]=useState(false);const [typed,setTyped]=useState("");
 const close=()=>{if(!pending){setOpen(false);setTyped("")}};
 useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!pending){setOpen(false);setTyped("")}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[open,pending]);
 return <><button type="button" className="danger small-button" onClick={()=>{if(confirm(`¿Eliminar a ${name} (${code})? Se borrará también todo su historial.`))setOpen(true)}}><Trash2 size={13}/>Eliminar</button>
 {open&&<div className="modal-backdrop" onClick={close}><div className="modal" role="alertdialog" aria-modal="true" aria-labelledby={`del-${id}`} onClick={e=>e.stopPropagation()}><TriangleAlert size={48} className="modal-danger-icon"/><h2 id={`del-${id}`}>Eliminar definitivamente a {name}</h2><p>Se borrarán de forma permanente:</p><ul><li>Todas sus marcas y jornadas, incluidas las correcciones</li><li>Sus turnos</li><li>Sus ausencias, vacaciones y movimientos de saldo</li><li>Sus líneas en planillas, aunque estén cerradas</li><li>Su PIN y sus datos personales</li></ul><p className="muted small">Esta acción no se puede deshacer. Solo quedará constancia en Auditoría.</p>
 <form action={formAction}><input type="hidden" name="id" value={id}/><label>Para confirmar, escribe el código <strong>{code}</strong><input name="confirm_code" value={typed} onChange={e=>setTyped(e.target.value.toUpperCase())} autoComplete="off" autoFocus disabled={pending}/></label>{state.error&&<p role="alert" className="alert error">{state.error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close} disabled={pending}>Cancelar</button><button className="danger-solid" disabled={pending||typed!==code}><Trash2 size={15}/>{pending?"Eliminando…":"Eliminar definitivamente"}</button></div></form></div></div>}</>;
}
