"use client";
import {useEffect,useRef,useState} from "react";import {LogIn,LogOut,Coffee,Play,CircleCheck,CircleX} from "lucide-react";import {punch} from "./actions";
const kinds=[{id:"entry",name:"Entrada",icon:LogIn},{id:"exit",name:"Salida",icon:LogOut},{id:"break_start",name:"Iniciar descanso",icon:Coffee},{id:"break_end",name:"Finalizar descanso",icon:Play}] as const;
export function Kiosk(){
 const [clock,setClock]=useState("");const [code,setCode]=useState("");const [pin,setPin]=useState("");const [kind,setKind]=useState<string>("entry");
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState<{error?:string;ok?:boolean;at?:string;kind?:string}>({});
 const open=Boolean(message.ok||message.error);const close=()=>setMessage({});
 const request=useRef<{key:string;id:string}|null>(null);const submitting=useRef(false);
 useEffect(()=>{const tick=()=>setClock(new Intl.DateTimeFormat("es-CR",{timeZone:"America/Costa_Rica",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date()));tick();const id=setInterval(tick,1000);return ()=>clearInterval(id)},[]);
 useEffect(()=>{if(!open)return;const id=setTimeout(()=>setMessage({}),message.ok?5000:10000);const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setMessage({})};window.addEventListener("keydown",onKey);return()=>{clearTimeout(id);window.removeEventListener("keydown",onKey)}},[open,message.ok]);
 async function submit(e:React.FormEvent){e.preventDefault();if(submitting.current)return;
 if(!navigator.onLine){setMessage({error:"Sin conexión. No se ha registrado la marca. Comunícate con el administrador."});return;}
 submitting.current=true;setBusy(true);setMessage({});const key=JSON.stringify([code,pin,kind]);
 if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};
 try{const result=await punch({code,pin,kind,requestId:request.current.id});setMessage({...result,kind:kinds.find(k=>k.id===kind)?.name});
 setCode("");setPin("");request.current=null;if(result.ok)setKind("entry");}
 catch{setMessage({error:"No se confirmó la marcación. Reintenta con los mismos datos."});}
 finally{submitting.current=false;setBusy(false);}
 }
 return <main className="kiosk"><div className="kiosk-body"><p className="eyebrow">BIENVENIDO A TU JORNADA</p><div className="clock" aria-label="Hora local">{clock||"--:--:--"}</div><p className="muted">Hora de Costa Rica · La marca se confirma con la hora del servidor</p><form onSubmit={submit} className="kiosk-form" autoComplete="off"><div className="two-col"><label>Código de empleado<input name="employee-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="GRT001" maxLength={12} autoComplete="off" spellCheck={false} data-lpignore="true" data-1p-ignore required disabled={busy}/></label><label>PIN personal<input name="employee-pin" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} type="password" inputMode="numeric" minLength={6} maxLength={8} autoComplete="new-password" data-lpignore="true" data-1p-ignore placeholder="••••••" required disabled={busy}/></label></div><div className="punch-options">{kinds.map(k=><button type="button" key={k.id} className={kind===k.id?"selected":""} aria-pressed={kind===k.id} disabled={busy} onClick={()=>setKind(k.id)}><k.icon size={26}/>{k.name}</button>)}</div><button className="primary wide" disabled={busy}>{busy?"Registrando…":"Confirmar marcación"}</button></form><p className="small muted">No compartas tu PIN. Si olvidaste una marca, consulta al administrador.</p></div>{open&&<div className="punch-modal-backdrop" onClick={close}><div className={`punch-modal ${message.ok?"success":"error"}`} role="alertdialog" aria-modal="true" aria-labelledby="punch-modal-title" aria-describedby="punch-modal-text" onClick={e=>e.stopPropagation()}>{message.ok?<CircleCheck size={72}/>:<CircleX size={72}/>}<h2 id="punch-modal-title">{message.ok?"Marcación registrada":"No se registró la marca"}</h2><p id="punch-modal-text">{message.ok?<>{message.kind} registrada a las <strong>{new Intl.DateTimeFormat("es-CR",{timeZone:"America/Costa_Rica",hour:"2-digit",minute:"2-digit"}).format(new Date(message.at!))}</strong>.</>:message.error}</p><button className="primary wide" onClick={close} autoFocus>Aceptar</button></div></div>}</main>;
}
